[package]
name = "dc_motor_speed_control_embassy"
version = "0.1.0"
edition = "2021"

[dependencies]
embassy-stm32 = { version = "0.6.0", features = ["stm32f103c8", "memory-x", "time-driver-any", "exti", "defmt", "unstable-pac"] }
embassy-executor = { version = "0.7.0", features = ["arch-cortex-m", "executor-thread"] }
embassy-time = { version = "0.5.0", features = ["tick-hz-32_768", "generic-queue-8", "defmt", "defmt-timestamp-uptime"] }
embassy-sync = "0.7.2"
embassy-futures = "0.1.1"

cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.3"
defmt = "1.0.1"
defmt-rtt = "1.1.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
embedded-hal = "1.0.0"
heapless = { version = "0.8", default-features = false }

[profile.release]
opt-level = "z"
debug = true
lto = true
